[2024-12-03T17:21:46.893+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.is_api_available scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:21:46.908+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.is_api_available scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:21:46.909+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:21:46.909+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-03T17:21:46.910+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:21:46.927+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-12-02 00:00:00+00:00
[2024-12-03T17:21:46.933+0000] {standard_task_runner.py:55} INFO - Started process 2719 to run task
[2024-12-03T17:21:46.938+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'practicional_dag', 'is_api_available', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmppv76dx_i']
[2024-12-03T17:21:46.941+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask is_api_available
[2024-12-03T17:21:47.052+0000] {task_command.py:376} INFO - Running <TaskInstance: practicional_dag.is_api_available scheduled__2024-12-02T00:00:00+00:00 [running]> on host 305bd4985967
[2024-12-03T17:21:47.165+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=practicional_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-12-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-02T00:00:00+00:00
[2024-12-03T17:21:47.166+0000] {http.py:120} INFO - Poking: api/
[2024-12-03T17:21:47.180+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-12-03T17:21:47.184+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-12-03T17:21:47.975+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-12-03T17:21:47.989+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=practicional_dag, task_id=is_api_available, execution_date=20241202T000000, start_date=20241203T172146, end_date=20241203T172147
[2024-12-03T17:21:48.023+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-12-03T17:21:48.050+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T17:34:06.326+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.is_api_available scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:34:06.340+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.is_api_available scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:34:06.341+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:34:06.341+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-03T17:34:06.341+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:34:06.361+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-12-02 00:00:00+00:00
[2024-12-03T17:34:06.367+0000] {standard_task_runner.py:55} INFO - Started process 3294 to run task
[2024-12-03T17:34:06.372+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'practicional_dag', 'is_api_available', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmphtsot32u']
[2024-12-03T17:34:06.375+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask is_api_available
[2024-12-03T17:34:06.462+0000] {task_command.py:376} INFO - Running <TaskInstance: practicional_dag.is_api_available scheduled__2024-12-02T00:00:00+00:00 [running]> on host 305bd4985967
[2024-12-03T17:34:06.550+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=practicional_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-12-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-02T00:00:00+00:00
[2024-12-03T17:34:06.552+0000] {http.py:120} INFO - Poking: api/
[2024-12-03T17:34:06.564+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-12-03T17:34:06.566+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-12-03T17:34:07.470+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-12-03T17:34:07.482+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=practicional_dag, task_id=is_api_available, execution_date=20241202T000000, start_date=20241203T173406, end_date=20241203T173407
[2024-12-03T17:34:07.535+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-12-03T17:34:07.582+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
