[2024-12-03T17:50:15.507+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_etl.is_api_available scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:50:15.520+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_etl.is_api_available scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:50:15.521+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:50:15.521+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-03T17:50:15.521+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:50:15.539+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-12-02 00:00:00+00:00
[2024-12-03T17:50:15.545+0000] {standard_task_runner.py:55} INFO - Started process 4043 to run task
[2024-12-03T17:50:15.550+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'practicional_etl', 'is_api_available', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpwjv16ezf']
[2024-12-03T17:50:15.553+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask is_api_available
[2024-12-03T17:50:15.646+0000] {task_command.py:376} INFO - Running <TaskInstance: practicional_etl.is_api_available scheduled__2024-12-02T00:00:00+00:00 [running]> on host 305bd4985967
[2024-12-03T17:50:15.738+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=practicional_etl
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-12-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-02T00:00:00+00:00
[2024-12-03T17:50:15.739+0000] {http.py:120} INFO - Poking: api/
[2024-12-03T17:50:15.752+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-12-03T17:50:15.754+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-12-03T17:50:16.781+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-12-03T17:50:16.796+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=practicional_etl, task_id=is_api_available, execution_date=20241202T000000, start_date=20241203T175015, end_date=20241203T175016
[2024-12-03T17:50:16.835+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-12-03T17:50:16.882+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
