[2024-12-03T17:21:45.105+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.create_table scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:21:45.116+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.create_table scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:21:45.117+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:21:45.117+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-03T17:21:45.117+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:21:45.137+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2024-12-02 00:00:00+00:00
[2024-12-03T17:21:45.144+0000] {standard_task_runner.py:55} INFO - Started process 2716 to run task
[2024-12-03T17:21:45.151+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'practicional_dag', 'create_table', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpmus3vfs8']
[2024-12-03T17:21:45.155+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask create_table
[2024-12-03T17:21:45.249+0000] {task_command.py:376} INFO - Running <TaskInstance: practicional_dag.create_table scheduled__2024-12-02T00:00:00+00:00 [running]> on host 305bd4985967
[2024-12-03T17:21:45.344+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=practicional_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-12-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-02T00:00:00+00:00
[2024-12-03T17:21:45.360+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-12-03T17:21:45.365+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2024-12-03T17:21:45.368+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2024-12-03T17:21:45.382+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=practicional_dag, task_id=create_table, execution_date=20241202T000000, start_date=20241203T172145, end_date=20241203T172145
[2024-12-03T17:21:45.411+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-12-03T17:21:45.451+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-03T17:34:04.498+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.create_table scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:34:04.511+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.create_table scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:34:04.512+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:34:04.512+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-03T17:34:04.513+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:34:04.531+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2024-12-02 00:00:00+00:00
[2024-12-03T17:34:04.537+0000] {standard_task_runner.py:55} INFO - Started process 3282 to run task
[2024-12-03T17:34:04.542+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'practicional_dag', 'create_table', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9m47lg82']
[2024-12-03T17:34:04.545+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask create_table
[2024-12-03T17:34:04.630+0000] {task_command.py:376} INFO - Running <TaskInstance: practicional_dag.create_table scheduled__2024-12-02T00:00:00+00:00 [running]> on host 305bd4985967
[2024-12-03T17:34:04.722+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=practicional_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-12-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-02T00:00:00+00:00
[2024-12-03T17:34:04.735+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-12-03T17:34:04.744+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2024-12-03T17:34:04.747+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2024-12-03T17:34:04.761+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=practicional_dag, task_id=create_table, execution_date=20241202T000000, start_date=20241203T173404, end_date=20241203T173404
[2024-12-03T17:34:04.804+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-12-03T17:34:04.885+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
